In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

from sklearn.metrics import confusion_matrix

from sklearn.utils import resample

from imblearn.over_sampling import SMOTE

In [2]:
#importing file
churn = pd.read_csv(r"C:\Users\pedro\Desktop\Ironhack\customer_churn.csv")
churn.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
#We will try to predict variable Churn using a logistic regression on variables tenure, SeniorCitizen ,MonthlyCharges
churn=churn[['Churn','tenure','SeniorCitizen','MonthlyCharges']]
churn.head(3)

Churn  tenure  SeniorCitizen  MonthlyCharges
0    No       1              0           29.85
1    No      34              0           56.95
2   Yes       2              0           53.85

In [4]:
#function to standardize headers

def standardize_headers(df):
    cols = []
    for i in range(len(df.columns)):
        cols.append(df.columns[i].lower().replace(' ','_'))
    df.columns = cols    
    return df#_data

In [5]:
churn=standardize_headers(churn)
churn.head(3)

churn  tenure  seniorcitizen  monthlycharges
0    No       1              0           29.85
1    No      34              0           56.95
2   Yes       2              0           53.85

In [6]:
#one hot encoding churn

churn['churn']=pd.get_dummies(churn['churn'])['Yes']
churn.head(3)

churn  tenure  seniorcitizen  monthlycharges
0      0       1              0           29.85
1      0      34              0           56.95
2      1       2              0           53.85

In [8]:
#checking NA's
def check_NA(df):
    print(df.isna().sum().sum())
    print("\n",df.isna().sum() / len(df))

In [9]:
#No NA's
check_NA(churn)

0

 churn             0.0
tenure            0.0
seniorcitizen     0.0
monthlycharges    0.0
dtype: float64


In [10]:
#counting churn/not churn 
churn['churn'].groupby(churn['churn']).count()

churn
0    5174
1    1869
Name: churn, dtype: int64

In [11]:
#Building and evaluating the logistic regression model.
X = churn.drop('churn', axis = 1)
y = churn['churn']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42, test_size = 0.2)

LR = LogisticRegression()
LR.fit(X_train, y_train)
pred = LR.predict(X_test)

accuracy_model1 = round(LR.score(X_test, y_test),3)
precision_model1 = round(precision_score(y_test, pred),3)
recall_model1 = round(recall_score(y_test, pred),3)
print ("Accuracy is:",accuracy_model1)
print("Precision is: ",precision_model1)
print("Recall is: ",recall_model1)
print("F1 is: ", round(f1_score(y_test, pred),3))
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))

Accuracy is: 0.806
Precision is:  0.691
Recall is:  0.48
F1 is:  0.566
              precision    recall  f1-score   support

           0       0.83      0.92      0.87      1036
           1       0.69      0.48      0.57       373

    accuracy                           0.81      1409
   macro avg       0.76      0.70      0.72      1409
weighted avg       0.79      0.81      0.79      1409

[[956  80]
 [194 179]]


In [12]:
# balancing data using the SMOTE method
sm = SMOTE(random_state = 0, sampling_strategy=1) 
X_train_SMOTE, y_train_SMOTE = sm.fit_resample(X_train,y_train)
train_smote = pd.concat([X_train_SMOTE,y_train_SMOTE], axis = 1)

In [13]:
# verifying if data is balanced
train_smote['churn'].groupby(train_smote['churn']).count()

churn
0    4138
1    4138
Name: churn, dtype: int64

In [14]:
#Building and evaluating the logistic regression model.
LR = LogisticRegression()
LR.fit(X_train_SMOTE, y_train_SMOTE)
pred = LR.predict(X_test)

accuracy_model2 = round(LR.score(X_test, y_test),3)
precision_model2 = round(precision_score(y_test, pred),3)
recall_model2 = round(recall_score(y_test, pred),3)
print ("Accuracy is:",accuracy_model2)
print("Precision is: ",precision_model2)
print("Recall is: ",recall_model2)
print("F1 is: ", round(f1_score(y_test, pred),3))
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))

Accuracy is: 0.745
Precision is:  0.513
Recall is:  0.759
F1 is:  0.612
              precision    recall  f1-score   support

           0       0.89      0.74      0.81      1036
           1       0.51      0.76      0.61       373

    accuracy                           0.75      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.79      0.75      0.76      1409

[[767 269]
 [ 90 283]]


In [15]:
#normalization

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalized_churn = pd.DataFrame(scaler.fit_transform(churn),columns=churn.columns)
normalized_churn.head(3)

churn    tenure  seniorcitizen  monthlycharges
0    0.0  0.013889            0.0        0.115423
1    0.0  0.472222            0.0        0.385075
2    1.0  0.027778            0.0        0.354229

In [16]:
#Building and evaluating the logistic regression model.
X = normalized_churn.drop('churn', axis = 1)
y = normalized_churn['churn']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42, test_size = 0.2)

LR = LogisticRegression()
LR.fit(X_train, y_train)
pred = LR.predict(X_test)

accuracy_model3 = round(LR.score(X_test, y_test),3)
precision_model3 = round(precision_score(y_test, pred),3)
recall_model3 = round(recall_score(y_test, pred),3)
print ("Accuracy is:",accuracy_model3)
print("Precision is: ",precision_model3)
print("Recall is: ",recall_model3)
print("F1 is: ", round(f1_score(y_test, pred),3))
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))

Accuracy is: 0.804
Precision is:  0.693
Recall is:  0.466
F1 is:  0.558
              precision    recall  f1-score   support

         0.0       0.83      0.93      0.87      1036
         1.0       0.69      0.47      0.56       373

    accuracy                           0.80      1409
   macro avg       0.76      0.70      0.72      1409
weighted avg       0.79      0.80      0.79      1409

[[959  77]
 [199 174]]


In [17]:
#Building and evaluating the logistic regression model using SMOTE.
sm = SMOTE(random_state = 0, sampling_strategy=1) # one means that I want a ratio of 1 between majority and abudance classe. # 0.5 Means my minority class will be half has big as my majority class
X_train_SMOTE, y_train_SMOTE = sm.fit_resample(X_train,y_train)
train_smote = pd.concat([X_train_SMOTE,y_train_SMOTE], axis = 1)
LR = LogisticRegression()
LR.fit(X_train_SMOTE, y_train_SMOTE)
pred = LR.predict(X_test)

accuracy_model4 = round(LR.score(X_test, y_test),3)
precision_model4 = round(precision_score(y_test, pred),3)
recall_model4 = round(recall_score(y_test, pred),3)
print ("Accuracy is:",accuracy_model4)
print("Precision is: ",precision_model4)
print("Recall is: ",recall_model4)
print("F1 is:", f1_score(y_test, pred))
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))


Accuracy is: 0.744
Precision is:  0.511
Recall is:  0.767
F1 is: 0.6130760986066451
              precision    recall  f1-score   support

         0.0       0.90      0.74      0.81      1036
         1.0       0.51      0.77      0.61       373

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.76      1409

[[762 274]
 [ 87 286]]


In [18]:
#Summary and comparison of the four models

d = {'model': ['imbalanced', 'SMOTE', 'normalized_imbalanced', 'normalized_SMOTE'],
     'accuracy': [accuracy_model1, accuracy_model2, accuracy_model3, accuracy_model4],
     'precision': [precision_model1, precision_model2, precision_model3, precision_model4], 
     'recall': [recall_model1, recall_model2, recall_model3, recall_model4]}
pd.DataFrame(d)


model  accuracy  precision  recall
0             imbalanced     0.806      0.691   0.480
1                  SMOTE     0.745      0.513   0.759
2  normalized_imbalanced     0.804      0.693   0.466
3       normalized_SMOTE     0.744      0.511   0.767